//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregatedCapacity) DeepCopyInto(out *AggregatedCapacity) {
	*out = *in
	if in.Flavors != nil {
		in, out := &in.Flavors, &out.Flavors
		*out = make([]AggregatedCapacityFlavor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregatedCapacity.
func (in *AggregatedCapacity) DeepCopy() *AggregatedCapacity {
	if in == nil {
		return nil
	}
	out := new(AggregatedCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregatedCapacityFlavor) DeepCopyInto(out *AggregatedCapacityFlavor) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregatedCapacityFlavor.
func (in *AggregatedCapacityFlavor) DeepCopy() *AggregatedCapacityFlavor {
	if in == nil {
		return nil
	}
	out := new(AggregatedCapacityFlavor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityDiscovery) DeepCopyInto(out *CapacityDiscovery) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]CapacityDiscoveryProviderContribution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityDiscovery.
func (in *CapacityDiscovery) DeepCopy() *CapacityDiscovery {
	if in == nil {
		return nil
	}
	out := new(CapacityDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityDiscoveryProviderContribution) DeepCopyInto(out *CapacityDiscoveryProviderContribution) {
	*out = *in
	if in.UsableCapacityPercent != nil {
		in, out := &in.UsableCapacityPercent, &out.UsableCapacityPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityDiscoveryProviderContribution.
func (in *CapacityDiscoveryProviderContribution) DeepCopy() *CapacityDiscoveryProviderContribution {
	if in == nil {
		return nil
	}
	out := new(CapacityDiscoveryProviderContribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityDistribution) DeepCopyInto(out *CapacityDistribution) {
	*out = *in
	out.SubtreeRootRef = in.SubtreeRootRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityDistribution.
func (in *CapacityDistribution) DeepCopy() *CapacityDistribution {
	if in == nil {
		return nil
	}
	out := new(CapacityDistribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityDistributionSubtreeRootRef) DeepCopyInto(out *CapacityDistributionSubtreeRootRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityDistributionSubtreeRootRef.
func (in *CapacityDistributionSubtreeRootRef) DeepCopy() *CapacityDistributionSubtreeRootRef {
	if in == nil {
		return nil
	}
	out := new(CapacityDistributionSubtreeRootRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityProvider) DeepCopyInto(out *CapacityProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityProvider.
func (in *CapacityProvider) DeepCopy() *CapacityProvider {
	if in == nil {
		return nil
	}
	out := new(CapacityProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityProviderList) DeepCopyInto(out *CapacityProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CapacityProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityProviderList.
func (in *CapacityProviderList) DeepCopy() *CapacityProviderList {
	if in == nil {
		return nil
	}
	out := new(CapacityProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityProviderManagedFlavor) DeepCopyInto(out *CapacityProviderManagedFlavor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityProviderManagedFlavor.
func (in *CapacityProviderManagedFlavor) DeepCopy() *CapacityProviderManagedFlavor {
	if in == nil {
		return nil
	}
	out := new(CapacityProviderManagedFlavor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityProviderParametersReference) DeepCopyInto(out *CapacityProviderParametersReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityProviderParametersReference.
func (in *CapacityProviderParametersReference) DeepCopy() *CapacityProviderParametersReference {
	if in == nil {
		return nil
	}
	out := new(CapacityProviderParametersReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityProviderSnapshot) DeepCopyInto(out *CapacityProviderSnapshot) {
	*out = *in
	if in.Flavors != nil {
		in, out := &in.Flavors, &out.Flavors
		*out = make([]CapacityProviderSnapshotFlavor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityProviderSnapshot.
func (in *CapacityProviderSnapshot) DeepCopy() *CapacityProviderSnapshot {
	if in == nil {
		return nil
	}
	out := new(CapacityProviderSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityProviderSnapshotFlavor) DeepCopyInto(out *CapacityProviderSnapshotFlavor) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityProviderSnapshotFlavor.
func (in *CapacityProviderSnapshotFlavor) DeepCopy() *CapacityProviderSnapshotFlavor {
	if in == nil {
		return nil
	}
	out := new(CapacityProviderSnapshotFlavor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityProviderSpec) DeepCopyInto(out *CapacityProviderSpec) {
	*out = *in
	if in.ManagedFlavors != nil {
		in, out := &in.ManagedFlavors, &out.ManagedFlavors
		*out = make([]CapacityProviderManagedFlavor, len(*in))
		copy(*out, *in)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(CapacityProviderParametersReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityProviderSpec.
func (in *CapacityProviderSpec) DeepCopy() *CapacityProviderSpec {
	if in == nil {
		return nil
	}
	out := new(CapacityProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityProviderStatus) DeepCopyInto(out *CapacityProviderStatus) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(CapacityProviderSnapshot)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityProviderStatus.
func (in *CapacityProviderStatus) DeepCopy() *CapacityProviderStatus {
	if in == nil {
		return nil
	}
	out := new(CapacityProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicQuotaOrchestrator) DeepCopyInto(out *DynamicQuotaOrchestrator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicQuotaOrchestrator.
func (in *DynamicQuotaOrchestrator) DeepCopy() *DynamicQuotaOrchestrator {
	if in == nil {
		return nil
	}
	out := new(DynamicQuotaOrchestrator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamicQuotaOrchestrator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicQuotaOrchestratorList) DeepCopyInto(out *DynamicQuotaOrchestratorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamicQuotaOrchestrator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicQuotaOrchestratorList.
func (in *DynamicQuotaOrchestratorList) DeepCopy() *DynamicQuotaOrchestratorList {
	if in == nil {
		return nil
	}
	out := new(DynamicQuotaOrchestratorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamicQuotaOrchestratorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicQuotaOrchestratorSpec) DeepCopyInto(out *DynamicQuotaOrchestratorSpec) {
	*out = *in
	in.CapacityDiscovery.DeepCopyInto(&out.CapacityDiscovery)
	if in.CapacityDistribution != nil {
		in, out := &in.CapacityDistribution, &out.CapacityDistribution
		*out = new(CapacityDistribution)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicQuotaOrchestratorSpec.
func (in *DynamicQuotaOrchestratorSpec) DeepCopy() *DynamicQuotaOrchestratorSpec {
	if in == nil {
		return nil
	}
	out := new(DynamicQuotaOrchestratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicQuotaOrchestratorStatus) DeepCopyInto(out *DynamicQuotaOrchestratorStatus) {
	*out = *in
	if in.AggregatedCapacity != nil {
		in, out := &in.AggregatedCapacity, &out.AggregatedCapacity
		*out = new(AggregatedCapacity)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicQuotaOrchestratorStatus.
func (in *DynamicQuotaOrchestratorStatus) DeepCopy() *DynamicQuotaOrchestratorStatus {
	if in == nil {
		return nil
	}
	out := new(DynamicQuotaOrchestratorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecifiedCapacity) DeepCopyInto(out *SpecifiedCapacity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecifiedCapacity.
func (in *SpecifiedCapacity) DeepCopy() *SpecifiedCapacity {
	if in == nil {
		return nil
	}
	out := new(SpecifiedCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpecifiedCapacity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecifiedCapacityFlavor) DeepCopyInto(out *SpecifiedCapacityFlavor) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecifiedCapacityFlavor.
func (in *SpecifiedCapacityFlavor) DeepCopy() *SpecifiedCapacityFlavor {
	if in == nil {
		return nil
	}
	out := new(SpecifiedCapacityFlavor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecifiedCapacityList) DeepCopyInto(out *SpecifiedCapacityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpecifiedCapacity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecifiedCapacityList.
func (in *SpecifiedCapacityList) DeepCopy() *SpecifiedCapacityList {
	if in == nil {
		return nil
	}
	out := new(SpecifiedCapacityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpecifiedCapacityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecifiedCapacitySpec) DeepCopyInto(out *SpecifiedCapacitySpec) {
	*out = *in
	if in.Flavors != nil {
		in, out := &in.Flavors, &out.Flavors
		*out = make([]SpecifiedCapacityFlavor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecifiedCapacitySpec.
func (in *SpecifiedCapacitySpec) DeepCopy() *SpecifiedCapacitySpec {
	if in == nil {
		return nil
	}
	out := new(SpecifiedCapacitySpec)
	in.DeepCopyInto(out)
	return out
}
