{{- if and .Values.enableMutatingAdmissionPolicy (.Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1/MutatingAdmissionPolicyBinding") }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: {{ include "kueue.fullname" . }}-clear-nominated-cluster-names-binding
  labels:
    {{- include "kueue.labels" . | nindent 4 }}
spec:
  policyName: {{ include "kueue.fullname" . }}-clear-nominated-cluster-names
{{- end }}
