# permissions for end users to view jobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appwrapper-viewer-role
  labels:
    rbac.kueue.x-k8s.io/role: "appwrapper-viewer"
    rbac.kueue.x-k8s.io/batch-admin: "true"
    rbac.kueue.x-k8s.io/batch-user: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - workload.codeflare.dev
  resources:
  - appwrappers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workload.codeflare.dev
  resources:
  - appwrappers/status
  verbs:
  - get
