# permissions for end users to view disaggregatedsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: disaggregatedset-viewer-role
  labels:
    rbac.kueue.x-k8s.io/role: "disaggregatedset-viewer"
    rbac.kueue.x-k8s.io/batch-admin: "true"
    rbac.kueue.x-k8s.io/batch-user: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - disaggregatedset.x-k8s.io
  resources:
  - disaggregatedsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - disaggregatedset.x-k8s.io
  resources:
  - disaggregatedsets/status
  verbs:
  - get
