/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
	testing "k8s.io/client-go/testing"
	v1beta2 "sigs.k8s.io/kueue/apis/visibility/v1beta2"
	visibilityv1beta2 "sigs.k8s.io/kueue/client-go/applyconfiguration/visibility/v1beta2"
	typedvisibilityv1beta2 "sigs.k8s.io/kueue/client-go/clientset/versioned/typed/visibility/v1beta2"
)

// fakeLocalQueues implements LocalQueueInterface
type fakeLocalQueues struct {
	*gentype.FakeClientWithListAndApply[*v1beta2.LocalQueue, *v1beta2.LocalQueueList, *visibilityv1beta2.LocalQueueApplyConfiguration]
	Fake *FakeVisibilityV1beta2
}

func newFakeLocalQueues(fake *FakeVisibilityV1beta2, namespace string) typedvisibilityv1beta2.LocalQueueInterface {
	return &fakeLocalQueues{
		gentype.NewFakeClientWithListAndApply[*v1beta2.LocalQueue, *v1beta2.LocalQueueList, *visibilityv1beta2.LocalQueueApplyConfiguration](
			fake.Fake,
			namespace,
			v1beta2.SchemeGroupVersion.WithResource("localqueues"),
			v1beta2.SchemeGroupVersion.WithKind("LocalQueue"),
			func() *v1beta2.LocalQueue { return &v1beta2.LocalQueue{} },
			func() *v1beta2.LocalQueueList { return &v1beta2.LocalQueueList{} },
			func(dst, src *v1beta2.LocalQueueList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta2.LocalQueueList) []*v1beta2.LocalQueue { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta2.LocalQueueList, items []*v1beta2.LocalQueue) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}

// GetPendingWorkloadsSummary takes name of the localQueue, and returns the corresponding pendingWorkloadsSummary object, and an error if there is any.
func (c *fakeLocalQueues) GetPendingWorkloadsSummary(ctx context.Context, localQueueName string, options v1.GetOptions) (result *v1beta2.PendingWorkloadsSummary, err error) {
	emptyResult := &v1beta2.PendingWorkloadsSummary{}
	obj, err := c.Fake.
		Invokes(testing.NewGetSubresourceActionWithOptions(c.Resource(), c.Namespace(), "pendingworkloads", localQueueName, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta2.PendingWorkloadsSummary), err
}
