/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// CohortLister helps list Cohorts.
// All objects returned here must be treated as read-only.
type CohortLister interface {
	// List lists all Cohorts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1beta1.Cohort, err error)
	// Cohorts returns an object that can list and get Cohorts.
	Cohorts(namespace string) CohortNamespaceLister
	CohortListerExpansion
}

// cohortLister implements the CohortLister interface.
type cohortLister struct {
	listers.ResourceIndexer[*kueuev1beta1.Cohort]
}

// NewCohortLister returns a new CohortLister.
func NewCohortLister(indexer cache.Indexer) CohortLister {
	return &cohortLister{listers.New[*kueuev1beta1.Cohort](indexer, kueuev1beta1.Resource("cohort"))}
}

// Cohorts returns an object that can list and get Cohorts.
func (s *cohortLister) Cohorts(namespace string) CohortNamespaceLister {
	return cohortNamespaceLister{listers.NewNamespaced[*kueuev1beta1.Cohort](s.ResourceIndexer, namespace)}
}

// CohortNamespaceLister helps list and get Cohorts.
// All objects returned here must be treated as read-only.
type CohortNamespaceLister interface {
	// List lists all Cohorts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1beta1.Cohort, err error)
	// Get retrieves the Cohort from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kueuev1beta1.Cohort, error)
	CohortNamespaceListerExpansion
}

// cohortNamespaceLister implements the CohortNamespaceLister
// interface.
type cohortNamespaceLister struct {
	listers.ResourceIndexer[*kueuev1beta1.Cohort]
}
