name: Update Krew Index
description: Updates the krew index with the new plugin version if it is the latest release.

inputs:
  version:
    description: Release version, formatted as vX.Y.Z (e.g. v0.10.0)
    required: true
  repo:
    description: Target repository in owner/name format
    required: true

runs:
  using: composite
  steps:
    - name: Check if latest release
      id: check_latest
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        VERSION: ${{ inputs.version }}
        TARGET_REPO: ${{ inputs.repo }}
      run: |
        LATEST_TAG=$(gh release view --repo "$TARGET_REPO" --json tagName --jq '.tagName')
        if [ "$LATEST_TAG" = "$VERSION" ]; then
          echo "result=true" >> "$GITHUB_OUTPUT"
        else
          echo "result=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Update new version in krew-index
      if: ${{ steps.check_latest.outputs.result == 'true' }}
      uses: docker://ghcr.io/rajatjindal/krew-release-bot:v0.0.51
      with:
        krew_plugin_release_tag: ${{ inputs.version }}
