/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// AutomatedQuotaManagementConfigApplyConfiguration represents a declarative configuration of the AutomatedQuotaManagementConfig type for use
// with apply.
//
// AutomatedQuotaManagementConfig is the configuration for the automated quota management in MultiKueue ClusterQueues.
type AutomatedQuotaManagementConfigApplyConfiguration struct {
	// aggregateResourceFlavorSpec is the specification of the resource flavor MultiKueue creates and maintains for the auto-aggregated resource flavors
	AggregateResourceFlavorSpec *ResourceFlavorSpecApplyConfiguration `json:"aggregateResourceFlavorSpec,omitempty"`
}

// AutomatedQuotaManagementConfigApplyConfiguration constructs a declarative configuration of the AutomatedQuotaManagementConfig type for use with
// apply.
func AutomatedQuotaManagementConfig() *AutomatedQuotaManagementConfigApplyConfiguration {
	return &AutomatedQuotaManagementConfigApplyConfiguration{}
}

// WithAggregateResourceFlavorSpec sets the AggregateResourceFlavorSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AggregateResourceFlavorSpec field is set to the value of the last call.
func (b *AutomatedQuotaManagementConfigApplyConfiguration) WithAggregateResourceFlavorSpec(value *ResourceFlavorSpecApplyConfiguration) *AutomatedQuotaManagementConfigApplyConfiguration {
	b.AggregateResourceFlavorSpec = value
	return b
}
