/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// ConcurrentAdmissionPolicyApplyConfiguration represents a declarative configuration of the ConcurrentAdmissionPolicy type for use
// with apply.
type ConcurrentAdmissionPolicyApplyConfiguration struct {
	// migration defines the constraints on Workload's migration.
	// The mechanism itself creates "Variants" of the same Workload, each pursuing a different flavor.
	// All Variants belong to the same "Parent" Workload, and are picked up by Kueue scheduler independently.
	// Once one of the Variants is admitted, the Parent Workload gets also admitted. The Variants that pursue more
	// favorable flavors keep trying to get admitted and if they succeed, the Workload migrates to the new flavor.
	// The Variants that pursue less favorable flavors are deactivated.
	// Flavor preferences are expressed through the order of flavors in the ClusterQueue.
	Migration *ConcurrentAdmissionMigrationApplyConfiguration `json:"migration,omitempty"`
}

// ConcurrentAdmissionPolicyApplyConfiguration constructs a declarative configuration of the ConcurrentAdmissionPolicy type for use with
// apply.
func ConcurrentAdmissionPolicy() *ConcurrentAdmissionPolicyApplyConfiguration {
	return &ConcurrentAdmissionPolicyApplyConfiguration{}
}

// WithMigration sets the Migration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Migration field is set to the value of the last call.
func (b *ConcurrentAdmissionPolicyApplyConfiguration) WithMigration(value *ConcurrentAdmissionMigrationApplyConfiguration) *ConcurrentAdmissionPolicyApplyConfiguration {
	b.Migration = value
	return b
}
