/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// EffectiveQuotaStatusApplyConfiguration represents a declarative configuration of the EffectiveQuotaStatus type for use
// with apply.
//
// EffectiveQuotaStatus represents the active effective quota structure computed by
// Dynamic Quota Orchestration (DQO).
type EffectiveQuotaStatusApplyConfiguration struct {
	// orchestratorRef identifies the component managing this value.
	OrchestratorRef *EffectiveQuotaStatusOrchestratorRefApplyConfiguration `json:"orchestratorRef,omitempty"`
	// resourceGroups is the effective quota used by the scheduler.
	// An empty list is a valid complete override and does not cause fallback to
	// spec.resourceGroups.
	ResourceGroups []ResourceGroupApplyConfiguration `json:"resourceGroups,omitempty"`
}

// EffectiveQuotaStatusApplyConfiguration constructs a declarative configuration of the EffectiveQuotaStatus type for use with
// apply.
func EffectiveQuotaStatus() *EffectiveQuotaStatusApplyConfiguration {
	return &EffectiveQuotaStatusApplyConfiguration{}
}

// WithOrchestratorRef sets the OrchestratorRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OrchestratorRef field is set to the value of the last call.
func (b *EffectiveQuotaStatusApplyConfiguration) WithOrchestratorRef(value *EffectiveQuotaStatusOrchestratorRefApplyConfiguration) *EffectiveQuotaStatusApplyConfiguration {
	b.OrchestratorRef = value
	return b
}

// WithResourceGroups adds the given value to the ResourceGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceGroups field.
func (b *EffectiveQuotaStatusApplyConfiguration) WithResourceGroups(values ...*ResourceGroupApplyConfiguration) *EffectiveQuotaStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResourceGroups")
		}
		b.ResourceGroups = append(b.ResourceGroups, *values[i])
	}
	return b
}
