/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// EffectiveQuotaStatusOrchestratorRefApplyConfiguration represents a declarative configuration of the EffectiveQuotaStatusOrchestratorRef type for use
// with apply.
//
// EffectiveQuotaStatusOrchestratorRef identifies the component managing the effective quota.
type EffectiveQuotaStatusOrchestratorRefApplyConfiguration struct {
	// apiGroup is the group for the resource representing the manager.
	APIGroup *string `json:"apiGroup,omitempty"`
	// kind is the type of the manager setting the effective quota.
	Kind *string `json:"kind,omitempty"`
	// name is the name of the manager setting the effective quota.
	Name *string `json:"name,omitempty"`
}

// EffectiveQuotaStatusOrchestratorRefApplyConfiguration constructs a declarative configuration of the EffectiveQuotaStatusOrchestratorRef type for use with
// apply.
func EffectiveQuotaStatusOrchestratorRef() *EffectiveQuotaStatusOrchestratorRefApplyConfiguration {
	return &EffectiveQuotaStatusOrchestratorRefApplyConfiguration{}
}

// WithAPIGroup sets the APIGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIGroup field is set to the value of the last call.
func (b *EffectiveQuotaStatusOrchestratorRefApplyConfiguration) WithAPIGroup(value string) *EffectiveQuotaStatusOrchestratorRefApplyConfiguration {
	b.APIGroup = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *EffectiveQuotaStatusOrchestratorRefApplyConfiguration) WithKind(value string) *EffectiveQuotaStatusOrchestratorRefApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *EffectiveQuotaStatusOrchestratorRefApplyConfiguration) WithName(value string) *EffectiveQuotaStatusOrchestratorRefApplyConfiguration {
	b.Name = &value
	return b
}
