/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// LocalQueueFairSharingStatusApplyConfiguration represents a declarative configuration of the LocalQueueFairSharingStatus type for use
// with apply.
//
// LocalQueueFairSharingStatus contains the information about the current status of Fair Sharing.
type LocalQueueFairSharingStatusApplyConfiguration struct {
	// weightedShare represents the maximum of the ratios of usage
	// above nominal quota to the lendable resources in the
	// Cohort, among all the resources provided by the Node, and
	// divided by the weight.  If zero, it means that the usage of
	// the Node is below the nominal quota.  If the Node has a
	// weight of zero and is borrowing, this will return
	// 9223372036854775807, the maximum possible share value.
	WeightedShare *int64 `json:"weightedShare,omitempty"`
	// admissionFairSharingStatus represents information relevant to the Admission Fair Sharing
	AdmissionFairSharingStatus *LocalQueueAdmissionFairSharingStatusApplyConfiguration `json:"admissionFairSharingStatus,omitempty"`
}

// LocalQueueFairSharingStatusApplyConfiguration constructs a declarative configuration of the LocalQueueFairSharingStatus type for use with
// apply.
func LocalQueueFairSharingStatus() *LocalQueueFairSharingStatusApplyConfiguration {
	return &LocalQueueFairSharingStatusApplyConfiguration{}
}

// WithWeightedShare sets the WeightedShare field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WeightedShare field is set to the value of the last call.
func (b *LocalQueueFairSharingStatusApplyConfiguration) WithWeightedShare(value int64) *LocalQueueFairSharingStatusApplyConfiguration {
	b.WeightedShare = &value
	return b
}

// WithAdmissionFairSharingStatus sets the AdmissionFairSharingStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdmissionFairSharingStatus field is set to the value of the last call.
func (b *LocalQueueFairSharingStatusApplyConfiguration) WithAdmissionFairSharingStatus(value *LocalQueueAdmissionFairSharingStatusApplyConfiguration) *LocalQueueFairSharingStatusApplyConfiguration {
	b.AdmissionFairSharingStatus = value
	return b
}
