/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// PodsetSliceRequiredTopologyConstraintApplyConfiguration represents a declarative configuration of the PodsetSliceRequiredTopologyConstraint type for use
// with apply.
//
// PodsetSliceRequiredTopologyConstraint defines a single slice topology constraint layer.
//
// Exactly one of size and sizes must be specified.
type PodsetSliceRequiredTopologyConstraintApplyConfiguration struct {
	// topology indicates the topology level required for this slice layer.
	Topology *string `json:"topology,omitempty"`
	// size indicates the number of pods in each equal chunk at this topology
	// level.
	Size *int32 `json:"size,omitempty"`
	// sizes lists the pod count of each chunk at this topology level, for
	// chunks that are not all the same size. Each chunk is placed within one
	// domain; chunks may share a domain. The sum must equal the chunk size of
	// the layer above, or the PodSet count for the first layer.
	//
	// The order of the list carries no meaning, and duplicate values describe
	// separate chunks of the same size.
	//
	// This field is alpha-level for the TASExactTopologyDistribution feature gate.
	Sizes []int32 `json:"sizes,omitempty"`
}

// PodsetSliceRequiredTopologyConstraintApplyConfiguration constructs a declarative configuration of the PodsetSliceRequiredTopologyConstraint type for use with
// apply.
func PodsetSliceRequiredTopologyConstraint() *PodsetSliceRequiredTopologyConstraintApplyConfiguration {
	return &PodsetSliceRequiredTopologyConstraintApplyConfiguration{}
}

// WithTopology sets the Topology field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Topology field is set to the value of the last call.
func (b *PodsetSliceRequiredTopologyConstraintApplyConfiguration) WithTopology(value string) *PodsetSliceRequiredTopologyConstraintApplyConfiguration {
	b.Topology = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *PodsetSliceRequiredTopologyConstraintApplyConfiguration) WithSize(value int32) *PodsetSliceRequiredTopologyConstraintApplyConfiguration {
	b.Size = &value
	return b
}

// WithSizes adds the given value to the Sizes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Sizes field.
func (b *PodsetSliceRequiredTopologyConstraintApplyConfiguration) WithSizes(values ...int32) *PodsetSliceRequiredTopologyConstraintApplyConfiguration {
	for i := range values {
		b.Sizes = append(b.Sizes, values[i])
	}
	return b
}
