/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// PriorityClassRefApplyConfiguration represents a declarative configuration of the PriorityClassRef type for use
// with apply.
type PriorityClassRefApplyConfiguration struct {
	Group *kueuev1beta2.PriorityClassGroup `json:"group,omitempty"`
	Kind  *kueuev1beta2.PriorityClassKind  `json:"kind,omitempty"`
	Name  *string                          `json:"name,omitempty"`
}

// PriorityClassRefApplyConfiguration constructs a declarative configuration of the PriorityClassRef type for use with
// apply.
func PriorityClassRef() *PriorityClassRefApplyConfiguration {
	return &PriorityClassRefApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *PriorityClassRefApplyConfiguration) WithGroup(value kueuev1beta2.PriorityClassGroup) *PriorityClassRefApplyConfiguration {
	b.Group = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *PriorityClassRefApplyConfiguration) WithKind(value kueuev1beta2.PriorityClassKind) *PriorityClassRefApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PriorityClassRefApplyConfiguration) WithName(value string) *PriorityClassRefApplyConfiguration {
	b.Name = &value
	return b
}
