/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// TopologyAssignmentSliceLevelIndividualValuesApplyConfiguration represents a declarative configuration of the TopologyAssignmentSliceLevelIndividualValues type for use
// with apply.
type TopologyAssignmentSliceLevelIndividualValuesApplyConfiguration struct {
	CommonPrefix *string  `json:"commonPrefix,omitempty"`
	CommonSuffix *string  `json:"commonSuffix,omitempty"`
	Roots        []string `json:"roots,omitempty"`
}

// TopologyAssignmentSliceLevelIndividualValuesApplyConfiguration constructs a declarative configuration of the TopologyAssignmentSliceLevelIndividualValues type for use with
// apply.
func TopologyAssignmentSliceLevelIndividualValues() *TopologyAssignmentSliceLevelIndividualValuesApplyConfiguration {
	return &TopologyAssignmentSliceLevelIndividualValuesApplyConfiguration{}
}

// WithCommonPrefix sets the CommonPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommonPrefix field is set to the value of the last call.
func (b *TopologyAssignmentSliceLevelIndividualValuesApplyConfiguration) WithCommonPrefix(value string) *TopologyAssignmentSliceLevelIndividualValuesApplyConfiguration {
	b.CommonPrefix = &value
	return b
}

// WithCommonSuffix sets the CommonSuffix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommonSuffix field is set to the value of the last call.
func (b *TopologyAssignmentSliceLevelIndividualValuesApplyConfiguration) WithCommonSuffix(value string) *TopologyAssignmentSliceLevelIndividualValuesApplyConfiguration {
	b.CommonSuffix = &value
	return b
}

// WithRoots adds the given value to the Roots field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Roots field.
func (b *TopologyAssignmentSliceLevelIndividualValuesApplyConfiguration) WithRoots(values ...string) *TopologyAssignmentSliceLevelIndividualValuesApplyConfiguration {
	for i := range values {
		b.Roots = append(b.Roots, values[i])
	}
	return b
}
