/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WaitForPodsReadyApplyConfiguration represents a declarative configuration of the WaitForPodsReady type for use
// with apply.
type WaitForPodsReadyApplyConfiguration struct {
	// podsReadyTimeout defines the maximum duration the workload may remain
	// admitted before all pods are in a Ready or Succeeded state.
	// When elapsed, the workload is evicted with reason PodsReadyTimeout.
	// If both this field and the cluster-wide WaitForPodsReady.Timeout are set,
	// this field takes precedence.
	PodsReadyTimeout *v1.Duration `json:"podsReadyTimeout,omitempty"`
}

// WaitForPodsReadyApplyConfiguration constructs a declarative configuration of the WaitForPodsReady type for use with
// apply.
func WaitForPodsReady() *WaitForPodsReadyApplyConfiguration {
	return &WaitForPodsReadyApplyConfiguration{}
}

// WithPodsReadyTimeout sets the PodsReadyTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodsReadyTimeout field is set to the value of the last call.
func (b *WaitForPodsReadyApplyConfiguration) WithPodsReadyTimeout(value v1.Duration) *WaitForPodsReadyApplyConfiguration {
	b.PodsReadyTimeout = &value
	return b
}
