/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	kueuev1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
	applyconfigurationkueuev1alpha1 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1alpha1"
	scheme "sigs.k8s.io/kueue/client-go/clientset/versioned/scheme"
)

// CapacityProvidersGetter has a method to return a CapacityProviderInterface.
// A group's client should implement this interface.
type CapacityProvidersGetter interface {
	CapacityProviders() CapacityProviderInterface
}

// CapacityProviderInterface has methods to work with CapacityProvider resources.
type CapacityProviderInterface interface {
	Create(ctx context.Context, capacityProvider *kueuev1alpha1.CapacityProvider, opts v1.CreateOptions) (*kueuev1alpha1.CapacityProvider, error)
	Update(ctx context.Context, capacityProvider *kueuev1alpha1.CapacityProvider, opts v1.UpdateOptions) (*kueuev1alpha1.CapacityProvider, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, capacityProvider *kueuev1alpha1.CapacityProvider, opts v1.UpdateOptions) (*kueuev1alpha1.CapacityProvider, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kueuev1alpha1.CapacityProvider, error)
	List(ctx context.Context, opts v1.ListOptions) (*kueuev1alpha1.CapacityProviderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kueuev1alpha1.CapacityProvider, err error)
	Apply(ctx context.Context, capacityProvider *applyconfigurationkueuev1alpha1.CapacityProviderApplyConfiguration, opts v1.ApplyOptions) (result *kueuev1alpha1.CapacityProvider, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, capacityProvider *applyconfigurationkueuev1alpha1.CapacityProviderApplyConfiguration, opts v1.ApplyOptions) (result *kueuev1alpha1.CapacityProvider, err error)
	CapacityProviderExpansion
}

// capacityProviders implements CapacityProviderInterface
type capacityProviders struct {
	*gentype.ClientWithListAndApply[*kueuev1alpha1.CapacityProvider, *kueuev1alpha1.CapacityProviderList, *applyconfigurationkueuev1alpha1.CapacityProviderApplyConfiguration]
}

// newCapacityProviders returns a CapacityProviders
func newCapacityProviders(c *KueueV1alpha1Client) *capacityProviders {
	return &capacityProviders{
		gentype.NewClientWithListAndApply[*kueuev1alpha1.CapacityProvider, *kueuev1alpha1.CapacityProviderList, *applyconfigurationkueuev1alpha1.CapacityProviderApplyConfiguration](
			"capacityproviders",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *kueuev1alpha1.CapacityProvider { return &kueuev1alpha1.CapacityProvider{} },
			func() *kueuev1alpha1.CapacityProviderList { return &kueuev1alpha1.CapacityProviderList{} },
		),
	}
}
