/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
	kueuev1alpha1 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1alpha1"
	scheme "sigs.k8s.io/kueue/client-go/clientset/versioned/scheme"
)

// MultiKueueClustersGetter has a method to return a MultiKueueClusterInterface.
// A group's client should implement this interface.
type MultiKueueClustersGetter interface {
	MultiKueueClusters() MultiKueueClusterInterface
}

// MultiKueueClusterInterface has methods to work with MultiKueueCluster resources.
type MultiKueueClusterInterface interface {
	Create(ctx context.Context, multiKueueCluster *v1alpha1.MultiKueueCluster, opts v1.CreateOptions) (*v1alpha1.MultiKueueCluster, error)
	Update(ctx context.Context, multiKueueCluster *v1alpha1.MultiKueueCluster, opts v1.UpdateOptions) (*v1alpha1.MultiKueueCluster, error)
	UpdateStatus(ctx context.Context, multiKueueCluster *v1alpha1.MultiKueueCluster, opts v1.UpdateOptions) (*v1alpha1.MultiKueueCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MultiKueueCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MultiKueueClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiKueueCluster, err error)
	Apply(ctx context.Context, multiKueueCluster *kueuev1alpha1.MultiKueueClusterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.MultiKueueCluster, err error)
	ApplyStatus(ctx context.Context, multiKueueCluster *kueuev1alpha1.MultiKueueClusterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.MultiKueueCluster, err error)
	MultiKueueClusterExpansion
}

// multiKueueClusters implements MultiKueueClusterInterface
type multiKueueClusters struct {
	client rest.Interface
}

// newMultiKueueClusters returns a MultiKueueClusters
func newMultiKueueClusters(c *KueueV1alpha1Client) *multiKueueClusters {
	return &multiKueueClusters{
		client: c.RESTClient(),
	}
}

// Get takes name of the multiKueueCluster, and returns the corresponding multiKueueCluster object, and an error if there is any.
func (c *multiKueueClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MultiKueueCluster, err error) {
	result = &v1alpha1.MultiKueueCluster{}
	err = c.client.Get().
		Resource("multikueueclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MultiKueueClusters that match those selectors.
func (c *multiKueueClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MultiKueueClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MultiKueueClusterList{}
	err = c.client.Get().
		Resource("multikueueclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested multiKueueClusters.
func (c *multiKueueClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("multikueueclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a multiKueueCluster and creates it.  Returns the server's representation of the multiKueueCluster, and an error, if there is any.
func (c *multiKueueClusters) Create(ctx context.Context, multiKueueCluster *v1alpha1.MultiKueueCluster, opts v1.CreateOptions) (result *v1alpha1.MultiKueueCluster, err error) {
	result = &v1alpha1.MultiKueueCluster{}
	err = c.client.Post().
		Resource("multikueueclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiKueueCluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a multiKueueCluster and updates it. Returns the server's representation of the multiKueueCluster, and an error, if there is any.
func (c *multiKueueClusters) Update(ctx context.Context, multiKueueCluster *v1alpha1.MultiKueueCluster, opts v1.UpdateOptions) (result *v1alpha1.MultiKueueCluster, err error) {
	result = &v1alpha1.MultiKueueCluster{}
	err = c.client.Put().
		Resource("multikueueclusters").
		Name(multiKueueCluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiKueueCluster).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *multiKueueClusters) UpdateStatus(ctx context.Context, multiKueueCluster *v1alpha1.MultiKueueCluster, opts v1.UpdateOptions) (result *v1alpha1.MultiKueueCluster, err error) {
	result = &v1alpha1.MultiKueueCluster{}
	err = c.client.Put().
		Resource("multikueueclusters").
		Name(multiKueueCluster.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiKueueCluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the multiKueueCluster and deletes it. Returns an error if one occurs.
func (c *multiKueueClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("multikueueclusters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *multiKueueClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("multikueueclusters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched multiKueueCluster.
func (c *multiKueueClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiKueueCluster, err error) {
	result = &v1alpha1.MultiKueueCluster{}
	err = c.client.Patch(pt).
		Resource("multikueueclusters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied multiKueueCluster.
func (c *multiKueueClusters) Apply(ctx context.Context, multiKueueCluster *kueuev1alpha1.MultiKueueClusterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.MultiKueueCluster, err error) {
	if multiKueueCluster == nil {
		return nil, fmt.Errorf("multiKueueCluster provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(multiKueueCluster)
	if err != nil {
		return nil, err
	}
	name := multiKueueCluster.Name
	if name == nil {
		return nil, fmt.Errorf("multiKueueCluster.Name must be provided to Apply")
	}
	result = &v1alpha1.MultiKueueCluster{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("multikueueclusters").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *multiKueueClusters) ApplyStatus(ctx context.Context, multiKueueCluster *kueuev1alpha1.MultiKueueClusterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.MultiKueueCluster, err error) {
	if multiKueueCluster == nil {
		return nil, fmt.Errorf("multiKueueCluster provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(multiKueueCluster)
	if err != nil {
		return nil, err
	}

	name := multiKueueCluster.Name
	if name == nil {
		return nil, fmt.Errorf("multiKueueCluster.Name must be provided to Apply")
	}

	result = &v1alpha1.MultiKueueCluster{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("multikueueclusters").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
