apiVersion: v2
name: kueue-priority-booster
description: A Helm chart for deploying the experimental Kueue priority-boost controller.
type: application
version: 0.18.4
appVersion: "v0.18.4"
dependencies:
  - name: kueue
    version: "~0.18.4"
    repository: "file://../../../../../charts/kueue"
    condition: kueue.enabled
