/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// AdmissionScopeApplyConfiguration represents a declarative configuration of the AdmissionScope type for use
// with apply.
type AdmissionScopeApplyConfiguration struct {
	AdmissionMode *kueuev1beta1.AdmissionMode `json:"admissionMode,omitempty"`
}

// AdmissionScopeApplyConfiguration constructs a declarative configuration of the AdmissionScope type for use with
// apply.
func AdmissionScope() *AdmissionScopeApplyConfiguration {
	return &AdmissionScopeApplyConfiguration{}
}

// WithAdmissionMode sets the AdmissionMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdmissionMode field is set to the value of the last call.
func (b *AdmissionScopeApplyConfiguration) WithAdmissionMode(value kueuev1beta1.AdmissionMode) *AdmissionScopeApplyConfiguration {
	b.AdmissionMode = &value
	return b
}
