/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AdmissionCheckSpecApplyConfiguration represents a declarative configuration of the AdmissionCheckSpec type for use
// with apply.
//
// AdmissionCheckSpec defines the desired state of AdmissionCheck
type AdmissionCheckSpecApplyConfiguration struct {
	// controllerName identifies the controller that processes the AdmissionCheck,
	// not necessarily a Kubernetes Pod or Deployment name. Cannot be empty.
	ControllerName *string `json:"controllerName,omitempty"`
	// retryDelayMinutes specifies how long to keep the workload suspended after
	// a failed check (after it transitioned to False). When the delay period has passed, the check
	// state goes to "Unknown". The default is 15 min.
	//
	// Deprecated: retryDelayMinutes has already been deprecated since v0.8 and will be removed in v1beta2.
	RetryDelayMinutes *int64 `json:"retryDelayMinutes,omitempty"`
	// parameters identifies a configuration with additional parameters for the
	// check.
	Parameters *AdmissionCheckParametersReferenceApplyConfiguration `json:"parameters,omitempty"`
}

// AdmissionCheckSpecApplyConfiguration constructs a declarative configuration of the AdmissionCheckSpec type for use with
// apply.
func AdmissionCheckSpec() *AdmissionCheckSpecApplyConfiguration {
	return &AdmissionCheckSpecApplyConfiguration{}
}

// WithControllerName sets the ControllerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControllerName field is set to the value of the last call.
func (b *AdmissionCheckSpecApplyConfiguration) WithControllerName(value string) *AdmissionCheckSpecApplyConfiguration {
	b.ControllerName = &value
	return b
}

// WithRetryDelayMinutes sets the RetryDelayMinutes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryDelayMinutes field is set to the value of the last call.
func (b *AdmissionCheckSpecApplyConfiguration) WithRetryDelayMinutes(value int64) *AdmissionCheckSpecApplyConfiguration {
	b.RetryDelayMinutes = &value
	return b
}

// WithParameters sets the Parameters field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Parameters field is set to the value of the last call.
func (b *AdmissionCheckSpecApplyConfiguration) WithParameters(value *AdmissionCheckParametersReferenceApplyConfiguration) *AdmissionCheckSpecApplyConfiguration {
	b.Parameters = value
	return b
}
