/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// BorrowWithinCohortApplyConfiguration represents a declarative configuration of the BorrowWithinCohort type for use
// with apply.
//
// BorrowWithinCohort contains configuration which allows to preempt workloads
// within cohort while borrowing. It only works with Classical Preemption,
// __not__ with Fair Sharing.
type BorrowWithinCohortApplyConfiguration struct {
	// policy determines the policy for preemption to reclaim quota within cohort while borrowing.
	// Possible values are:
	// - `Never` (default): do not allow for preemption, in other
	// ClusterQueues within the cohort, for a borrowing workload.
	// - `LowerPriority`: allow preemption, in other ClusterQueues
	// within the cohort, for a borrowing workload, but only if
	// the preempted workloads are of lower priority.
	Policy *kueuev1beta1.BorrowWithinCohortPolicy `json:"policy,omitempty"`
	// maxPriorityThreshold allows to restrict the set of workloads which
	// might be preempted by a borrowing workload, to only workloads with
	// priority less than or equal to the specified threshold priority.
	// When the threshold is not specified, then any workload satisfying the
	// policy can be preempted by the borrowing workload.
	MaxPriorityThreshold *int32 `json:"maxPriorityThreshold,omitempty"`
}

// BorrowWithinCohortApplyConfiguration constructs a declarative configuration of the BorrowWithinCohort type for use with
// apply.
func BorrowWithinCohort() *BorrowWithinCohortApplyConfiguration {
	return &BorrowWithinCohortApplyConfiguration{}
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *BorrowWithinCohortApplyConfiguration) WithPolicy(value kueuev1beta1.BorrowWithinCohortPolicy) *BorrowWithinCohortApplyConfiguration {
	b.Policy = &value
	return b
}

// WithMaxPriorityThreshold sets the MaxPriorityThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxPriorityThreshold field is set to the value of the last call.
func (b *BorrowWithinCohortApplyConfiguration) WithMaxPriorityThreshold(value int32) *BorrowWithinCohortApplyConfiguration {
	b.MaxPriorityThreshold = &value
	return b
}
