/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ProvisioningRequestPodSetUpdatesApplyConfiguration represents a declarative configuration of the ProvisioningRequestPodSetUpdates type for use
// with apply.
type ProvisioningRequestPodSetUpdatesApplyConfiguration struct {
	NodeSelector []ProvisioningRequestPodSetUpdatesNodeSelectorApplyConfiguration `json:"nodeSelector,omitempty"`
}

// ProvisioningRequestPodSetUpdatesApplyConfiguration constructs a declarative configuration of the ProvisioningRequestPodSetUpdates type for use with
// apply.
func ProvisioningRequestPodSetUpdates() *ProvisioningRequestPodSetUpdatesApplyConfiguration {
	return &ProvisioningRequestPodSetUpdatesApplyConfiguration{}
}

// WithNodeSelector adds the given value to the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NodeSelector field.
func (b *ProvisioningRequestPodSetUpdatesApplyConfiguration) WithNodeSelector(values ...*ProvisioningRequestPodSetUpdatesNodeSelectorApplyConfiguration) *ProvisioningRequestPodSetUpdatesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNodeSelector")
		}
		b.NodeSelector = append(b.NodeSelector, *values[i])
	}
	return b
}
