/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// ProvisioningRequestConfigSpecApplyConfiguration represents a declarative configuration of the ProvisioningRequestConfigSpec type for use
// with apply.
//
// ProvisioningRequestConfigSpec defines the desired state of ProvisioningRequestConfig
type ProvisioningRequestConfigSpecApplyConfiguration struct {
	// provisioningClassName describes the different modes of provisioning the resources.
	// Check autoscaling.x-k8s.io ProvisioningRequestSpec.ProvisioningClassName for details.
	ProvisioningClassName *string `json:"provisioningClassName,omitempty"`
	// parameters contains all other parameters classes may require.
	Parameters map[string]kueuev1beta1.Parameter `json:"parameters,omitempty"`
	// managedResources contains the list of resources managed by the autoscaling.
	//
	// If empty, all resources are considered managed.
	//
	// If not empty, the ProvisioningRequest will contain only the podsets that are
	// requesting at least one of them.
	//
	// If none of the workloads podsets is requesting at least a managed resource,
	// the workload is considered ready.
	ManagedResources []v1.ResourceName `json:"managedResources,omitempty"`
	// retryStrategy defines strategy for retrying ProvisioningRequest.
	// If null, then the default configuration is applied with the following parameter values:
	// backoffLimitCount:  3
	// backoffBaseSeconds: 60 - 1 min
	// backoffMaxSeconds:  1800 - 30 mins
	//
	// To switch off retry mechanism
	// set retryStrategy.backoffLimitCount to 0.
	RetryStrategy *ProvisioningRequestRetryStrategyApplyConfiguration `json:"retryStrategy,omitempty"`
	// podSetUpdates specifies the update of the workload's PodSetUpdates which
	// are used to target the provisioned nodes.
	PodSetUpdates *ProvisioningRequestPodSetUpdatesApplyConfiguration `json:"podSetUpdates,omitempty"`
	// podSetMergePolicy specifies the policy for merging PodSets before being passed
	// to the cluster autoscaler.
	PodSetMergePolicy *kueuev1beta1.ProvisioningRequestConfigPodSetMergePolicy `json:"podSetMergePolicy,omitempty"`
}

// ProvisioningRequestConfigSpecApplyConfiguration constructs a declarative configuration of the ProvisioningRequestConfigSpec type for use with
// apply.
func ProvisioningRequestConfigSpec() *ProvisioningRequestConfigSpecApplyConfiguration {
	return &ProvisioningRequestConfigSpecApplyConfiguration{}
}

// WithProvisioningClassName sets the ProvisioningClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProvisioningClassName field is set to the value of the last call.
func (b *ProvisioningRequestConfigSpecApplyConfiguration) WithProvisioningClassName(value string) *ProvisioningRequestConfigSpecApplyConfiguration {
	b.ProvisioningClassName = &value
	return b
}

// WithParameters puts the entries into the Parameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Parameters field,
// overwriting an existing map entries in Parameters field with the same key.
func (b *ProvisioningRequestConfigSpecApplyConfiguration) WithParameters(entries map[string]kueuev1beta1.Parameter) *ProvisioningRequestConfigSpecApplyConfiguration {
	if b.Parameters == nil && len(entries) > 0 {
		b.Parameters = make(map[string]kueuev1beta1.Parameter, len(entries))
	}
	for k, v := range entries {
		b.Parameters[k] = v
	}
	return b
}

// WithManagedResources adds the given value to the ManagedResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ManagedResources field.
func (b *ProvisioningRequestConfigSpecApplyConfiguration) WithManagedResources(values ...v1.ResourceName) *ProvisioningRequestConfigSpecApplyConfiguration {
	for i := range values {
		b.ManagedResources = append(b.ManagedResources, values[i])
	}
	return b
}

// WithRetryStrategy sets the RetryStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryStrategy field is set to the value of the last call.
func (b *ProvisioningRequestConfigSpecApplyConfiguration) WithRetryStrategy(value *ProvisioningRequestRetryStrategyApplyConfiguration) *ProvisioningRequestConfigSpecApplyConfiguration {
	b.RetryStrategy = value
	return b
}

// WithPodSetUpdates sets the PodSetUpdates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSetUpdates field is set to the value of the last call.
func (b *ProvisioningRequestConfigSpecApplyConfiguration) WithPodSetUpdates(value *ProvisioningRequestPodSetUpdatesApplyConfiguration) *ProvisioningRequestConfigSpecApplyConfiguration {
	b.PodSetUpdates = value
	return b
}

// WithPodSetMergePolicy sets the PodSetMergePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSetMergePolicy field is set to the value of the last call.
func (b *ProvisioningRequestConfigSpecApplyConfiguration) WithPodSetMergePolicy(value kueuev1beta1.ProvisioningRequestConfigPodSetMergePolicy) *ProvisioningRequestConfigSpecApplyConfiguration {
	b.PodSetMergePolicy = &value
	return b
}
