/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// ProvisioningRequestPodSetUpdateApplyConfiguration represents a declarative configuration of the ProvisioningRequestPodSetUpdate type for use
// with apply.
type ProvisioningRequestPodSetUpdateApplyConfiguration struct {
	Type            *kueuev1beta1.ProvisioningRequestPodSetUpdateType `json:"type,omitempty"`
	Key             *string                                           `json:"key,omitempty"`
	ValueFromDetail *string                                           `json:"valueFromDetail,omitempty"`
}

// ProvisioningRequestPodSetUpdateApplyConfiguration constructs a declarative configuration of the ProvisioningRequestPodSetUpdate type for use with
// apply.
func ProvisioningRequestPodSetUpdate() *ProvisioningRequestPodSetUpdateApplyConfiguration {
	return &ProvisioningRequestPodSetUpdateApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ProvisioningRequestPodSetUpdateApplyConfiguration) WithType(value kueuev1beta1.ProvisioningRequestPodSetUpdateType) *ProvisioningRequestPodSetUpdateApplyConfiguration {
	b.Type = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ProvisioningRequestPodSetUpdateApplyConfiguration) WithKey(value string) *ProvisioningRequestPodSetUpdateApplyConfiguration {
	b.Key = &value
	return b
}

// WithValueFromDetail sets the ValueFromDetail field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValueFromDetail field is set to the value of the last call.
func (b *ProvisioningRequestPodSetUpdateApplyConfiguration) WithValueFromDetail(value string) *ProvisioningRequestPodSetUpdateApplyConfiguration {
	b.ValueFromDetail = &value
	return b
}
