/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// ResourceGroupApplyConfiguration represents a declarative configuration of the ResourceGroup type for use
// with apply.
type ResourceGroupApplyConfiguration struct {
	// coveredResources is the list of resources covered by the flavors in this
	// group.
	// Examples: cpu, memory, vendor.com/gpu.
	// The list cannot be empty and it can contain up to 64 resources. With a total
	// of up to 256 covered resources across all resource groups in the ClusterQueue.
	CoveredResources []v1.ResourceName `json:"coveredResources,omitempty"`
	// flavors is the list of flavors that provide the resources of this group.
	// Typically, different flavors represent different hardware models
	// (e.g., gpu models, cpu architectures) or pricing models (on-demand vs spot
	// cpus).
	// Each flavor MUST list all the resources listed for this group in the same
	// order as the .resources field.
	// The list cannot be empty and it can contain up to 64 flavors, with a max of
	// 256 total flavors across all resource groups in the ClusterQueue.
	Flavors []FlavorQuotasApplyConfiguration `json:"flavors,omitempty"`
}

// ResourceGroupApplyConfiguration constructs a declarative configuration of the ResourceGroup type for use with
// apply.
func ResourceGroup() *ResourceGroupApplyConfiguration {
	return &ResourceGroupApplyConfiguration{}
}

// WithCoveredResources adds the given value to the CoveredResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CoveredResources field.
func (b *ResourceGroupApplyConfiguration) WithCoveredResources(values ...v1.ResourceName) *ResourceGroupApplyConfiguration {
	for i := range values {
		b.CoveredResources = append(b.CoveredResources, values[i])
	}
	return b
}

// WithFlavors adds the given value to the Flavors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Flavors field.
func (b *ResourceGroupApplyConfiguration) WithFlavors(values ...*FlavorQuotasApplyConfiguration) *ResourceGroupApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFlavors")
		}
		b.Flavors = append(b.Flavors, *values[i])
	}
	return b
}
