/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// ResourceGroupApplyConfiguration represents a declarative configuration of the ResourceGroup type for use
// with apply.
type ResourceGroupApplyConfiguration struct {
	CoveredResources []v1.ResourceName                `json:"coveredResources,omitempty"`
	Flavors          []FlavorQuotasApplyConfiguration `json:"flavors,omitempty"`
}

// ResourceGroupApplyConfiguration constructs a declarative configuration of the ResourceGroup type for use with
// apply.
func ResourceGroup() *ResourceGroupApplyConfiguration {
	return &ResourceGroupApplyConfiguration{}
}

// WithCoveredResources adds the given value to the CoveredResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CoveredResources field.
func (b *ResourceGroupApplyConfiguration) WithCoveredResources(values ...v1.ResourceName) *ResourceGroupApplyConfiguration {
	for i := range values {
		b.CoveredResources = append(b.CoveredResources, values[i])
	}
	return b
}

// WithFlavors adds the given value to the Flavors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Flavors field.
func (b *ResourceGroupApplyConfiguration) WithFlavors(values ...*FlavorQuotasApplyConfiguration) *ResourceGroupApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFlavors")
		}
		b.Flavors = append(b.Flavors, *values[i])
	}
	return b
}
