/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// TopologyAssignmentRecoveryApplyConfiguration represents a declarative configuration of the TopologyAssignmentRecovery type for use
// with apply.
type TopologyAssignmentRecoveryApplyConfiguration struct {
	NodesToReplace []string `json:"nodesToReplace,omitempty"`
}

// TopologyAssignmentRecoveryApplyConfiguration constructs a declarative configuration of the TopologyAssignmentRecovery type for use with
// apply.
func TopologyAssignmentRecovery() *TopologyAssignmentRecoveryApplyConfiguration {
	return &TopologyAssignmentRecoveryApplyConfiguration{}
}

// WithNodesToReplace adds the given value to the NodesToReplace field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NodesToReplace field.
func (b *TopologyAssignmentRecoveryApplyConfiguration) WithNodesToReplace(values ...string) *TopologyAssignmentRecoveryApplyConfiguration {
	for i := range values {
		b.NodesToReplace = append(b.NodesToReplace, values[i])
	}
	return b
}
