/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// WallTimeFlavorApplyConfiguration represents a declarative configuration of the WallTimeFlavor type for use
// with apply.
type WallTimeFlavorApplyConfiguration struct {
	Name                        *kueuev1beta1.ResourceFlavorReference `json:"name,omitempty"`
	WallTimeAllocatedHours      *int32                                `json:"wallTimeAllocatedHours,omitempty"`
	ActionWhenWallTimeExhausted *kueuev1beta1.StopPolicy              `json:"actionWhenWallTimeExhausted,omitempty"`
}

// WallTimeFlavorApplyConfiguration constructs a declarative configuration of the WallTimeFlavor type for use with
// apply.
func WallTimeFlavor() *WallTimeFlavorApplyConfiguration {
	return &WallTimeFlavorApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *WallTimeFlavorApplyConfiguration) WithName(value kueuev1beta1.ResourceFlavorReference) *WallTimeFlavorApplyConfiguration {
	b.Name = &value
	return b
}

// WithWallTimeAllocatedHours sets the WallTimeAllocatedHours field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WallTimeAllocatedHours field is set to the value of the last call.
func (b *WallTimeFlavorApplyConfiguration) WithWallTimeAllocatedHours(value int32) *WallTimeFlavorApplyConfiguration {
	b.WallTimeAllocatedHours = &value
	return b
}

// WithActionWhenWallTimeExhausted sets the ActionWhenWallTimeExhausted field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActionWhenWallTimeExhausted field is set to the value of the last call.
func (b *WallTimeFlavorApplyConfiguration) WithActionWhenWallTimeExhausted(value kueuev1beta1.StopPolicy) *WallTimeFlavorApplyConfiguration {
	b.ActionWhenWallTimeExhausted = &value
	return b
}
