/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// WithinClusterQueueConfigApplyConfiguration represents a declarative configuration of the WithinClusterQueueConfig type for use
// with apply.
//
// WithinClusterQueueConfig provides time-based preemption controls for
// workloads within a ClusterQueue.
type WithinClusterQueueConfigApplyConfiguration struct {
	// minAdmitDurationSeconds specifies the minimum number of seconds an
	// incumbent workload (one that was queued before the pending workload)
	// must be admitted before it becomes eligible for preemption within the
	// ClusterQueue.
	MinAdmitDurationSeconds *int32 `json:"minAdmitDurationSeconds,omitempty"`
	// opportunisticMinAdmitDurationSeconds specifies the minimum number of
	// seconds a workload that was queued after the pending workload but
	// admitted first (because it fit in remaining capacity) must be admitted
	// before it becomes eligible for preemption.
	OpportunisticMinAdmitDurationSeconds *int32 `json:"opportunisticMinAdmitDurationSeconds,omitempty"`
}

// WithinClusterQueueConfigApplyConfiguration constructs a declarative configuration of the WithinClusterQueueConfig type for use with
// apply.
func WithinClusterQueueConfig() *WithinClusterQueueConfigApplyConfiguration {
	return &WithinClusterQueueConfigApplyConfiguration{}
}

// WithMinAdmitDurationSeconds sets the MinAdmitDurationSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinAdmitDurationSeconds field is set to the value of the last call.
func (b *WithinClusterQueueConfigApplyConfiguration) WithMinAdmitDurationSeconds(value int32) *WithinClusterQueueConfigApplyConfiguration {
	b.MinAdmitDurationSeconds = &value
	return b
}

// WithOpportunisticMinAdmitDurationSeconds sets the OpportunisticMinAdmitDurationSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpportunisticMinAdmitDurationSeconds field is set to the value of the last call.
func (b *WithinClusterQueueConfigApplyConfiguration) WithOpportunisticMinAdmitDurationSeconds(value int32) *WithinClusterQueueConfigApplyConfiguration {
	b.OpportunisticMinAdmitDurationSeconds = &value
	return b
}
