// Copyright The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: sigs.k8s.io/kueue/pkg/controller/tas (interfaces: NodeTASCache)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/tas/interface.go -copyright_file hack/boilerplate.txt -package mocks sigs.k8s.io/kueue/pkg/controller/tas NodeTASCache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockNodeTASCache is a mock of NodeTASCache interface.
type MockNodeTASCache struct {
	ctrl     *gomock.Controller
	recorder *MockNodeTASCacheMockRecorder
	isgomock struct{}
}

// MockNodeTASCacheMockRecorder is the mock recorder for MockNodeTASCache.
type MockNodeTASCacheMockRecorder struct {
	mock *MockNodeTASCache
}

// NewMockNodeTASCache creates a new mock instance.
func NewMockNodeTASCache(ctrl *gomock.Controller) *MockNodeTASCache {
	mock := &MockNodeTASCache{ctrl: ctrl}
	mock.recorder = &MockNodeTASCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeTASCache) EXPECT() *MockNodeTASCacheMockRecorder {
	return m.recorder
}

// AddOrUpdateNode mocks base method.
func (m *MockNodeTASCache) AddOrUpdateNode(node *v1.Node) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddOrUpdateNode", node)
}

// AddOrUpdateNode indicates an expected call of AddOrUpdateNode.
func (mr *MockNodeTASCacheMockRecorder) AddOrUpdateNode(node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrUpdateNode", reflect.TypeOf((*MockNodeTASCache)(nil).AddOrUpdateNode), node)
}

// DeleteNode mocks base method.
func (m *MockNodeTASCache) DeleteNode(nodeName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteNode", nodeName)
}

// DeleteNode indicates an expected call of DeleteNode.
func (mr *MockNodeTASCacheMockRecorder) DeleteNode(nodeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNode", reflect.TypeOf((*MockNodeTASCache)(nil).DeleteNode), nodeName)
}
