apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpi-operator
  namespace: mpi-operator
spec:
  template:
    spec:
      containers:
        - name: mpi-operator
          args:
            - --leader-elect-lease-duration=60s
            - --leader-elect-renew-deadline=40s
            - --leader-elect-retry-period=10s
            - --kube-api-qps=50
            - --kube-api-burst=100