/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1beta2 "sigs.k8s.io/kueue/client-go/clientset/versioned/typed/kueue/v1beta2"
)

type FakeKueueV1beta2 struct {
	*testing.Fake
}

func (c *FakeKueueV1beta2) AdmissionChecks() v1beta2.AdmissionCheckInterface {
	return newFakeAdmissionChecks(c)
}

func (c *FakeKueueV1beta2) ClusterQueues() v1beta2.ClusterQueueInterface {
	return newFakeClusterQueues(c)
}

func (c *FakeKueueV1beta2) Cohorts() v1beta2.CohortInterface {
	return newFakeCohorts(c)
}

func (c *FakeKueueV1beta2) LocalQueues(namespace string) v1beta2.LocalQueueInterface {
	return newFakeLocalQueues(c, namespace)
}

func (c *FakeKueueV1beta2) MultiKueueClusters() v1beta2.MultiKueueClusterInterface {
	return newFakeMultiKueueClusters(c)
}

func (c *FakeKueueV1beta2) MultiKueueConfigs() v1beta2.MultiKueueConfigInterface {
	return newFakeMultiKueueConfigs(c)
}

func (c *FakeKueueV1beta2) ProvisioningRequestConfigs() v1beta2.ProvisioningRequestConfigInterface {
	return newFakeProvisioningRequestConfigs(c)
}

func (c *FakeKueueV1beta2) ResourceFlavors() v1beta2.ResourceFlavorInterface {
	return newFakeResourceFlavors(c)
}

func (c *FakeKueueV1beta2) Topologies() v1beta2.TopologyInterface {
	return newFakeTopologies(c)
}

func (c *FakeKueueV1beta2) Workloads(namespace string) v1beta2.WorkloadInterface {
	return newFakeWorkloads(c, namespace)
}

func (c *FakeKueueV1beta2) WorkloadPriorityClasses() v1beta2.WorkloadPriorityClassInterface {
	return newFakeWorkloadPriorityClasses(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKueueV1beta2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
