/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
	applyconfigurationkueuev1beta1 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1beta1"
	scheme "sigs.k8s.io/kueue/client-go/clientset/versioned/scheme"
)

// WorkloadsGetter has a method to return a WorkloadInterface.
// A group's client should implement this interface.
type WorkloadsGetter interface {
	Workloads(namespace string) WorkloadInterface
}

// WorkloadInterface has methods to work with Workload resources.
type WorkloadInterface interface {
	Create(ctx context.Context, workload *kueuev1beta1.Workload, opts v1.CreateOptions) (*kueuev1beta1.Workload, error)
	Update(ctx context.Context, workload *kueuev1beta1.Workload, opts v1.UpdateOptions) (*kueuev1beta1.Workload, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, workload *kueuev1beta1.Workload, opts v1.UpdateOptions) (*kueuev1beta1.Workload, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kueuev1beta1.Workload, error)
	List(ctx context.Context, opts v1.ListOptions) (*kueuev1beta1.WorkloadList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kueuev1beta1.Workload, err error)
	Apply(ctx context.Context, workload *applyconfigurationkueuev1beta1.WorkloadApplyConfiguration, opts v1.ApplyOptions) (result *kueuev1beta1.Workload, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, workload *applyconfigurationkueuev1beta1.WorkloadApplyConfiguration, opts v1.ApplyOptions) (result *kueuev1beta1.Workload, err error)
	WorkloadExpansion
}

// workloads implements WorkloadInterface
type workloads struct {
	*gentype.ClientWithListAndApply[*kueuev1beta1.Workload, *kueuev1beta1.WorkloadList, *applyconfigurationkueuev1beta1.WorkloadApplyConfiguration]
}

// newWorkloads returns a Workloads
func newWorkloads(c *KueueV1beta1Client, namespace string) *workloads {
	return &workloads{
		gentype.NewClientWithListAndApply[*kueuev1beta1.Workload, *kueuev1beta1.WorkloadList, *applyconfigurationkueuev1beta1.WorkloadApplyConfiguration](
			"workloads",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kueuev1beta1.Workload { return &kueuev1beta1.Workload{} },
			func() *kueuev1beta1.WorkloadList { return &kueuev1beta1.WorkloadList{} },
		),
	}
}
