/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "sigs.k8s.io/kueue/client-go/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// AdmissionChecks returns a AdmissionCheckInformer.
	AdmissionChecks() AdmissionCheckInformer
	// ClusterQueues returns a ClusterQueueInformer.
	ClusterQueues() ClusterQueueInformer
	// LocalQueues returns a LocalQueueInformer.
	LocalQueues() LocalQueueInformer
	// MultiKueueClusters returns a MultiKueueClusterInformer.
	MultiKueueClusters() MultiKueueClusterInformer
	// MultiKueueConfigs returns a MultiKueueConfigInformer.
	MultiKueueConfigs() MultiKueueConfigInformer
	// ProvisioningRequestConfigs returns a ProvisioningRequestConfigInformer.
	ProvisioningRequestConfigs() ProvisioningRequestConfigInformer
	// ResourceFlavors returns a ResourceFlavorInformer.
	ResourceFlavors() ResourceFlavorInformer
	// Workloads returns a WorkloadInformer.
	Workloads() WorkloadInformer
	// WorkloadPriorityClasses returns a WorkloadPriorityClassInformer.
	WorkloadPriorityClasses() WorkloadPriorityClassInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// AdmissionChecks returns a AdmissionCheckInformer.
func (v *version) AdmissionChecks() AdmissionCheckInformer {
	return &admissionCheckInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ClusterQueues returns a ClusterQueueInformer.
func (v *version) ClusterQueues() ClusterQueueInformer {
	return &clusterQueueInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalQueues returns a LocalQueueInformer.
func (v *version) LocalQueues() LocalQueueInformer {
	return &localQueueInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MultiKueueClusters returns a MultiKueueClusterInformer.
func (v *version) MultiKueueClusters() MultiKueueClusterInformer {
	return &multiKueueClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// MultiKueueConfigs returns a MultiKueueConfigInformer.
func (v *version) MultiKueueConfigs() MultiKueueConfigInformer {
	return &multiKueueConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ProvisioningRequestConfigs returns a ProvisioningRequestConfigInformer.
func (v *version) ProvisioningRequestConfigs() ProvisioningRequestConfigInformer {
	return &provisioningRequestConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ResourceFlavors returns a ResourceFlavorInformer.
func (v *version) ResourceFlavors() ResourceFlavorInformer {
	return &resourceFlavorInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Workloads returns a WorkloadInformer.
func (v *version) Workloads() WorkloadInformer {
	return &workloadInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// WorkloadPriorityClasses returns a WorkloadPriorityClassInformer.
func (v *version) WorkloadPriorityClasses() WorkloadPriorityClassInformer {
	return &workloadPriorityClassInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
