resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

patches:
- target:
    kind: MutatingWebhookConfiguration
    name: mutating-webhook-configuration
  patch: |-
    - op: add
      path: /webhooks/0/namespaceSelector
      value:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
            - kube-system
            - kueue-system


# as kustomize does not allow * targeting in path, we use replacements
# to apply the same namespaceSelector to all webhooks
replacements:
- source:
    kind: MutatingWebhookConfiguration
    name: mutating-webhook-configuration
    fieldPath: webhooks.0.namespaceSelector
  targets:
    - select:
        kind: MutatingWebhookConfiguration
        name: mutating-webhook-configuration
      fieldPaths:
        - webhooks.*.namespaceSelector
      options:
        create: true
    - select:
        kind: ValidatingWebhookConfiguration
        name: validating-webhook-configuration
      fieldPaths:
        - webhooks.*.namespaceSelector
      options:
        create: true
