apiVersion: agents.x-k8s.io/v1alpha1
kind: Sandbox
metadata:
  name: hello-world-kueue
spec:
  podTemplate:
    metadata:
      labels:
        kueue.x-k8s.io/queue-name: user-queue
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["sleep"]
        args: ["6000"]
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
      restartPolicy: Never
