on:
  release:
    types: [released]
jobs:
  krew-release:
    if: ${{ github.repository == 'kubernetes-sigs/kueue' && !github.event.release.prerelease }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Update new version in krew-index
        uses: ./.github/actions/update-krew-index
        with:
          version: ${{ github.event.release.tag_name }}
          repo: ${{ github.repository }}
