on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

permissions: {}

jobs:
  vexctl:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Generate OpenVEX
        uses: ./.github/actions/generate-openvex
        with:
          tag: ${{ inputs.tag }}
