on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

permissions: {}

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Install bom and generate SBOM
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Generate SBOM
        uses: ./.github/actions/generate-sbom
        with:
          tag: ${{ inputs.tag }}
