/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// MultiKueueClusterLister helps list MultiKueueClusters.
// All objects returned here must be treated as read-only.
type MultiKueueClusterLister interface {
	// List lists all MultiKueueClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1beta2.MultiKueueCluster, err error)
	// Get retrieves the MultiKueueCluster from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kueuev1beta2.MultiKueueCluster, error)
	MultiKueueClusterListerExpansion
}

// multiKueueClusterLister implements the MultiKueueClusterLister interface.
type multiKueueClusterLister struct {
	listers.ResourceIndexer[*kueuev1beta2.MultiKueueCluster]
}

// NewMultiKueueClusterLister returns a new MultiKueueClusterLister.
func NewMultiKueueClusterLister(indexer cache.Indexer) MultiKueueClusterLister {
	return &multiKueueClusterLister{listers.New[*kueuev1beta2.MultiKueueCluster](indexer, kueuev1beta2.Resource("multikueuecluster"))}
}
