/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	kueuev1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
)

// CapacityProviderNormalizedCapacityFlavorApplyConfiguration represents a declarative configuration of the CapacityProviderNormalizedCapacityFlavor type for use
// with apply.
type CapacityProviderNormalizedCapacityFlavorApplyConfiguration struct {
	// name identifies the ResourceFlavor whose capacity is reported.
	Name *kueuev1alpha1.ResourceFlavorReference `json:"name,omitempty"`
	// resources contains total capacity by resource name.
	Resources *v1.ResourceList `json:"resources,omitempty"`
}

// CapacityProviderNormalizedCapacityFlavorApplyConfiguration constructs a declarative configuration of the CapacityProviderNormalizedCapacityFlavor type for use with
// apply.
func CapacityProviderNormalizedCapacityFlavor() *CapacityProviderNormalizedCapacityFlavorApplyConfiguration {
	return &CapacityProviderNormalizedCapacityFlavorApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CapacityProviderNormalizedCapacityFlavorApplyConfiguration) WithName(value kueuev1alpha1.ResourceFlavorReference) *CapacityProviderNormalizedCapacityFlavorApplyConfiguration {
	b.Name = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *CapacityProviderNormalizedCapacityFlavorApplyConfiguration) WithResources(value v1.ResourceList) *CapacityProviderNormalizedCapacityFlavorApplyConfiguration {
	b.Resources = &value
	return b
}
