/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	kueuev1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
)

// CapacityDiscoveryProviderContributionApplyConfiguration represents a declarative configuration of the CapacityDiscoveryProviderContribution type for use
// with apply.
type CapacityDiscoveryProviderContributionApplyConfiguration struct {
	// name identifies a CapacityProvider.
	Name *kueuev1alpha1.CapacityProviderName `json:"name,omitempty"`
	// effectiveCapacityMultiplier specifies the multiplier applied to the
	// discovered capacity from this provider. It defaults to 1.
	EffectiveCapacityMultiplier *resource.Quantity `json:"effectiveCapacityMultiplier,omitempty"`
}

// CapacityDiscoveryProviderContributionApplyConfiguration constructs a declarative configuration of the CapacityDiscoveryProviderContribution type for use with
// apply.
func CapacityDiscoveryProviderContribution() *CapacityDiscoveryProviderContributionApplyConfiguration {
	return &CapacityDiscoveryProviderContributionApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CapacityDiscoveryProviderContributionApplyConfiguration) WithName(value kueuev1alpha1.CapacityProviderName) *CapacityDiscoveryProviderContributionApplyConfiguration {
	b.Name = &value
	return b
}

// WithEffectiveCapacityMultiplier sets the EffectiveCapacityMultiplier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EffectiveCapacityMultiplier field is set to the value of the last call.
func (b *CapacityDiscoveryProviderContributionApplyConfiguration) WithEffectiveCapacityMultiplier(value resource.Quantity) *CapacityDiscoveryProviderContributionApplyConfiguration {
	b.EffectiveCapacityMultiplier = &value
	return b
}
