/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	kueuev1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
)

// DynamicResourceApplyConfiguration represents a declarative configuration of the DynamicResource type for use
// with apply.
type DynamicResourceApplyConfiguration struct {
	Name             *kueuev1alpha1.DriverResourceName  `json:"name,omitempty"`
	DeviceClassNames []kueuev1alpha1.DriverResourceName `json:"deviceClassNames,omitempty"`
}

// DynamicResourceApplyConfiguration constructs a declarative configuration of the DynamicResource type for use with
// apply.
func DynamicResource() *DynamicResourceApplyConfiguration {
	return &DynamicResourceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DynamicResourceApplyConfiguration) WithName(value kueuev1alpha1.DriverResourceName) *DynamicResourceApplyConfiguration {
	b.Name = &value
	return b
}

// WithDeviceClassNames adds the given value to the DeviceClassNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DeviceClassNames field.
func (b *DynamicResourceApplyConfiguration) WithDeviceClassNames(values ...kueuev1alpha1.DriverResourceName) *DynamicResourceApplyConfiguration {
	for i := range values {
		b.DeviceClassNames = append(b.DeviceClassNames, values[i])
	}
	return b
}
