/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	kueuev1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
)

// PreemptionConfigPriorityConstraintApplyConfiguration represents a declarative configuration of the PreemptionConfigPriorityConstraint type for use
// with apply.
//
// PreemptionConfigPriorityConstraint defines how candidate priority is evaluated.
type PreemptionConfigPriorityConstraintApplyConfiguration struct {
	// mode specifies which priority value to compare.
	// Must be specified together with comparison.
	//
	Mode *kueuev1alpha1.PreemptionConfigPriorityMode `json:"mode,omitempty"`
	// comparison is the relational operator comparing the candidate's priority
	// against the preemptor's priority (i.e., <candidate> <comparison> <preemptor>).
	// For example, LessThan means the candidate must have strictly lower priority than the preemptor.
	// Must be specified together with mode.
	//
	Comparison *kueuev1alpha1.NumericComparison `json:"comparison,omitempty"`
	// PreemptionConfigPriorityClassSelector filters candidate workloads by priority class name.
	PreemptionConfigPriorityClassSelectorApplyConfiguration `json:""`
}

// PreemptionConfigPriorityConstraintApplyConfiguration constructs a declarative configuration of the PreemptionConfigPriorityConstraint type for use with
// apply.
func PreemptionConfigPriorityConstraint() *PreemptionConfigPriorityConstraintApplyConfiguration {
	return &PreemptionConfigPriorityConstraintApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *PreemptionConfigPriorityConstraintApplyConfiguration) WithMode(value kueuev1alpha1.PreemptionConfigPriorityMode) *PreemptionConfigPriorityConstraintApplyConfiguration {
	b.Mode = &value
	return b
}

// WithComparison sets the Comparison field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Comparison field is set to the value of the last call.
func (b *PreemptionConfigPriorityConstraintApplyConfiguration) WithComparison(value kueuev1alpha1.NumericComparison) *PreemptionConfigPriorityConstraintApplyConfiguration {
	b.Comparison = &value
	return b
}

// WithMatchNames adds the given value to the MatchNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MatchNames field.
func (b *PreemptionConfigPriorityConstraintApplyConfiguration) WithMatchNames(values ...string) *PreemptionConfigPriorityConstraintApplyConfiguration {
	for i := range values {
		b.PreemptionConfigPriorityClassSelectorApplyConfiguration.MatchNames = append(b.PreemptionConfigPriorityClassSelectorApplyConfiguration.MatchNames, values[i])
	}
	return b
}

// WithNotMatchNames adds the given value to the NotMatchNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NotMatchNames field.
func (b *PreemptionConfigPriorityConstraintApplyConfiguration) WithNotMatchNames(values ...string) *PreemptionConfigPriorityConstraintApplyConfiguration {
	for i := range values {
		b.PreemptionConfigPriorityClassSelectorApplyConfiguration.NotMatchNames = append(b.PreemptionConfigPriorityClassSelectorApplyConfiguration.NotMatchNames, values[i])
	}
	return b
}
