/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	kueuev1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
)

// PreemptionConfigActivationPolicyApplyConfiguration represents a declarative configuration of the PreemptionConfigActivationPolicy type for use
// with apply.
//
// PreemptionConfigActivationPolicy defines when a preemption rule contributes candidates.
type PreemptionConfigActivationPolicyApplyConfiguration struct {
	// trigger specifies the prerequisite for contributing candidates.
	//
	// Possible values are:
	// - Always: contributes matching candidates unconditionally.
	// - InsufficientQuota: contributes matching candidates only if preempting baseline candidates
	// does not yield sufficient quota to admit the preemptor workload.
	// - QuotaFeasibleAndInsufficientTopology: contributes matching candidates only if quota
	// is feasible for the entire preemptor under at least one eligible flavor assignment
	// (after preempting baseline candidates and any candidates from InsufficientQuota rules),
	// but the workload cannot be admitted because no eligible flavor assignment satisfies
	// its topology requirements.
	//
	// Baseline candidates are the deduplicated union of:
	// - candidates selected by the preemptor's ClusterQueue.spec.preemption policy;
	// - candidates selected by applicable rules in the referenced PreemptionConfig
	// whose activationPolicy.trigger is Always.
	//
	Trigger *kueuev1alpha1.PreemptionConfigActivationTrigger `json:"trigger,omitempty"`
}

// PreemptionConfigActivationPolicyApplyConfiguration constructs a declarative configuration of the PreemptionConfigActivationPolicy type for use with
// apply.
func PreemptionConfigActivationPolicy() *PreemptionConfigActivationPolicyApplyConfiguration {
	return &PreemptionConfigActivationPolicyApplyConfiguration{}
}

// WithTrigger sets the Trigger field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Trigger field is set to the value of the last call.
func (b *PreemptionConfigActivationPolicyApplyConfiguration) WithTrigger(value kueuev1alpha1.PreemptionConfigActivationTrigger) *PreemptionConfigActivationPolicyApplyConfiguration {
	b.Trigger = &value
	return b
}
