/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PreemptionConfigPriorityClassSelectorApplyConfiguration represents a declarative configuration of the PreemptionConfigPriorityClassSelector type for use
// with apply.
//
// PreemptionConfigPriorityClassSelector filters workloads by their priority class name
// (matched against the Workload's spec.priorityClassRef.name, which is populated by Kueue
// for both WorkloadPriorityClass and Pod PriorityClass).
// When WorkloadPriorityClassDefaulting is enabled and a "default" WorkloadPriorityClass exists,
// or when a globalDefault Pod PriorityClass is configured, its name (e.g., "default") can be used
// in matchNames or notMatchNames to match or exclude workloads that do not explicitly specify a priority class.
type PreemptionConfigPriorityClassSelectorApplyConfiguration struct {
	// matchNames is an allowlist of PriorityClass or WorkloadPriorityClass names.
	// If specified, a workload matches only if its spec.priorityClassRef.name equals
	// any name in this list (OR semantics); if specified workloads without a priorityClassRef do not match. If not specified does not impose any class names restrictions on workloads.
	//
	MatchNames []string `json:"matchNames,omitempty"`
	// notMatchNames is a denylist of PriorityClass or WorkloadPriorityClass names.
	// If specified, a workload matches only if its spec.priorityClassRef.name does not equal
	// any name in this list; workloads without a priorityClassRef always match. If not specified does not impose any class names restrictions on workloads.
	// If both matchNames and notMatchNames are specified, both conditions must be satisfied (AND semantics).
	//
	NotMatchNames []string `json:"notMatchNames,omitempty"`
}

// PreemptionConfigPriorityClassSelectorApplyConfiguration constructs a declarative configuration of the PreemptionConfigPriorityClassSelector type for use with
// apply.
func PreemptionConfigPriorityClassSelector() *PreemptionConfigPriorityClassSelectorApplyConfiguration {
	return &PreemptionConfigPriorityClassSelectorApplyConfiguration{}
}

// WithMatchNames adds the given value to the MatchNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MatchNames field.
func (b *PreemptionConfigPriorityClassSelectorApplyConfiguration) WithMatchNames(values ...string) *PreemptionConfigPriorityClassSelectorApplyConfiguration {
	for i := range values {
		b.MatchNames = append(b.MatchNames, values[i])
	}
	return b
}

// WithNotMatchNames adds the given value to the NotMatchNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NotMatchNames field.
func (b *PreemptionConfigPriorityClassSelectorApplyConfiguration) WithNotMatchNames(values ...string) *PreemptionConfigPriorityClassSelectorApplyConfiguration {
	for i := range values {
		b.NotMatchNames = append(b.NotMatchNames, values[i])
	}
	return b
}
